### ISSUE TITLE
Crashes 2.0.1 Patch

### ISSUE THREAD

**Issue by chrispiciullo** [jac3km4/cybercmd#6]
Looks like this needs updating for the 2.0.1 patch. Using the CET version the game crashes immediately on launch with this error.
![2023-10-07 12_24_25-Error](https://github.com/jac3km4/cybercmd/assets/2933774/ef300357-88a3-43c7-bee1-cea3d53de70d)

**Comment by jac3km4** [comment]
this errors is typically caused by red4ext startup errors, not cybercmd, you should check the red4ext logs in `red4ext\logs\red4ext.log`

**Comment by chrispiciullo** [comment]
You, sir, are a life saver. Turns out there was a Red4Ext update just this morning. It was pure coincidence that I did a fresh re-install and was going through mods one by one where cybercmd  triggered it. With the updated version of red4ext, everything is working again. I'll go ahead and mark this closes as everything is good to go once again. Thanks!
